=== j4ckk0/XsdViewer/samples/purchaseOrder.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Sample schema, adapted from the purchase-order example of "XML Schema Part 0: Primer" (https://www.w3.org/TR/xmlschema-0/), Copyright W3C, reused under the W3C Document License. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:po="http://example.com/po"
           xmlns:ext="http://example.com/ext"
           targetNamespace="http://example.com/po"
           elementFormDefault="qualified">

  <xs:import namespace="http://example.com/ext" schemaLocation="ext.xsd"/>

  <xs:annotation>
    <xs:documentation>
      Purchase order schema for Example.com.
      Copyright 2000 Example.com. All rights reserved.
    </xs:documentation>
  </xs:annotation>

  <xs:element name="purchaseOrder" type="po:PurchaseOrderType">
    <xs:annotation>
      <xs:documentation>Root element of a purchase order document.</xs:documentation>
    </xs:annotation>
  </xs:element>

  <xs:element name="comment" type="xs:string"/>

  <xs:element name="urgentComment" type="xs:string" substitutionGroup="po:comment"/>

  <xs:complexType name="PurchaseOrderType">
    <xs:sequence>
      <xs:element name="shipTo" type="po:USAddress"/>
      <xs:element name="billTo" type="po:USAddress"/>
      <xs:element ref="po:comment" minOccurs="0"/>
      <xs:element name="items" type="po:Items"/>
    </xs:sequence>
    <xs:attribute name="orderDate" type="xs:date"/>
    <xs:attributeGroup ref="po:AuditAttributes"/>
  </xs:complexType>

  <xs:complexType name="USAddress">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="street" type="xs:string"/>
      <xs:element name="city" type="xs:string"/>
      <xs:element name="state" type="xs:string"/>
      <xs:element name="zip" type="xs:decimal"/>
    </xs:sequence>
    <xs:attribute name="country" type="xs:NMTOKEN" fixed="US"/>
  </xs:complexType>

  <xs:complexType name="Items">
    <xs:sequence>
      <xs:element name="item" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="productName" type="xs:string"/>
            <xs:element name="quantity">
              <xs:simpleType>
                <xs:restriction base="xs:positiveInteger">
                  <xs:maxExclusive value="100"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:element>
            <xs:element name="USPrice" type="xs:decimal"/>
            <xs:element ref="po:comment" minOccurs="0"/>
            <xs:element name="shipDate" type="xs:date" minOccurs="0"/>
            <xs:group ref="po:ItemExtras" minOccurs="0"/>
          </xs:sequence>
          <xs:attribute name="partNum" type="po:SKU" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:group name="ItemExtras">
    <xs:sequence>
      <xs:element name="giftWrap" type="xs:boolean"/>
      <xs:element name="giftMessage" type="po:Message"/>
    </xs:sequence>
  </xs:group>

  <xs:attributeGroup name="AuditAttributes">
    <xs:attribute name="createdBy" type="xs:string"/>
    <xs:attribute ref="po:version"/>
  </xs:attributeGroup>

  <xs:attribute name="version" type="xs:token"/>

  <!-- Stock Keeping Unit, a code for identifying products -->
  <xs:simpleType name="SKU">
    <xs:annotation>
      <xs:documentation>Stock Keeping Unit, e.g. 123-AB.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:pattern value="\d{3}-[A-Z]{2}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="Message">
    <xs:restriction base="po:LimitedText"/>
  </xs:simpleType>

  <xs:simpleType
      name="LimitedText">
    <xs:restriction base="xs:string">
      <xs:maxLength value="200"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="SKUList">
    <xs:list itemType="po:SKU"/>
  </xs:simpleType>

  <xs:simpleType name="Identifier">
    <xs:union memberTypes="po:SKU xs:positiveInteger"/>
  </xs:simpleType>

  <!-- An enumeration: the details panel lists its values -->
  <xs:simpleType name="Currency">
    <xs:annotation>
      <xs:documentation>The currencies a price may be given in.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="USD">
        <xs:annotation>
          <xs:documentation>US dollar</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="EUR">
        <xs:annotation>
          <xs:documentation>Euro</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="GBP"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="InternationalAddress">
    <xs:complexContent>
      <xs:extension base="po:USAddress">
        <xs:sequence>
          <xs:element name="countryName" type="xs:string"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <!-- A recursive type: a category may contain sub-categories; its label's type comes from ext.xsd -->
  <xs:complexType name="Category">
    <xs:sequence>
      <xs:element name="subCategory" type="po:Category" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="label" type="ext:Label"/>
  </xs:complexType>

</xs:schema>

=== j4ckk0/XsdViewer/samples/purchaseOrder.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- A purchase order valid against purchaseOrder.xsd and passing every rule of schematron/purchaseOrder.sch.
     To see the rules fire: set a quantity to 100, drop the comment of the expensive item, or ship an item before the order date. -->
<po:purchaseOrder xmlns:po="http://example.com/po"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://example.com/po purchaseOrder.xsd"
                  orderDate="2026-09-01" createdBy="alice" po:version="1.0">
  <po:shipTo country="US">
    <po:name>Alice Smith</po:name>
    <po:street>123 Maple Street</po:street>
    <po:city>Mill Valley</po:city>
    <po:state>CA</po:state>
    <po:zip>90952</po:zip>
  </po:shipTo>
  <po:billTo country="US">
    <po:name>Robert Smith</po:name>
    <po:street>8 Oak Avenue</po:street>
    <po:city>Old Town</po:city>
    <po:state>PA</po:state>
    <po:zip>95819</po:zip>
  </po:billTo>
  <po:comment>Hurry, my lawn is going wild!</po:comment>
  <po:items>
    <po:item partNum="872-AA">
      <po:productName>Lawnmower</po:productName>
      <po:quantity>1</po:quantity>
      <po:USPrice>1480.00</po:USPrice>
      <po:comment>Confirm this is electric</po:comment>
      <po:shipDate>2026-09-03</po:shipDate>
    </po:item>
    <po:item partNum="926-AA">
      <po:productName>Baby Monitor</po:productName>
      <po:quantity>2</po:quantity>
      <po:USPrice>39.98</po:USPrice>
      <po:shipDate>2026-09-05</po:shipDate>
      <po:giftWrap>true</po:giftWrap>
      <po:giftMessage>For the new arrival</po:giftMessage>
    </po:item>
  </po:items>
</po:purchaseOrder>
